version: "3.5"
services:
  selenium-hub:
    image: selenium/hub:3.141
    container_name: selenium-hub
#    ports:
#      - "4444:4444"
    networks:
      - selenium

  chrome:
    image: selenium/node-chrome:3.141
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - selenium
  firefox:
    image: selenium/node-firefox:3.141
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - selenium
networks:
  selenium:
    name: selenium
